### ISSUE TITLE
NameError("name 'mygtk' is not defined",)

### ISSUE THREAD

**Issue by waiferv** [jwagner/playitslowly#10]
Hi, 

when I start playitslowly 1.5.0 in Debian jessie I get:

```
An error has occured:
NameError("name 'mygtk' is not defined",)
You should save your work and restart the application. If the error occurs again please report it to the developer.

NameError
Python 3.4.2: /usr/bin/python3
Wed Feb 17 19:25:13 2016

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /usr/lib/python3.4/runpy.py in _run_module_as_main(mod_name='playitslowly.app', alter_argv=1)
  168         sys.argv[0] = mod_spec.origin
  169     return _run_code(code, main_globals, None,
  170                      "__main__", mod_spec)
  171 
  172 def run_module(mod_name, init_globals=None,
mod_spec = ModuleSpec(name='playitslowly.app', loader=<_fro...lib/python3.4/dist-packages/playitslowly/app.py')

 /usr/lib/python3.4/runpy.py in _run_code(code=<code object <module> at 0xb71ee160, file "/usr/...n3.4/dist-packages/playitslowly/app.py", line 21>, run_globals={'CONFIG_PATH': '/home/soren/.config/playitslowly.json', 'Config': <class '__main__.Config'>, 'GObject': <gi.module.DynamicModule 'GObject' from '/usr/li...-linux-gnu/girepository-1.0/GObject-2.0.typelib'>, 'Gdk': <gi.module.DynamicModule 'Gdk' from '/usr/lib/i386-linux-gnu/girepository-1.0/Gdk-3.0.typelib'>, 'Gio': <gi.module.DynamicModule 'Gio' from '/usr/lib/i386-linux-gnu/girepository-1.0/Gio-2.0.typelib'>, 'Gst': <gi.module.DynamicModule 'Gst' from '/usr/lib/girepository-1.0/Gst-1.0.typelib'>, 'GstColorBalance': <class 'playitslowly.pipeline.__main__.GstColorBalance'>, 'GstNavigation': <class 'playitslowly.pipeline.__main__.GstNavigation'>, 'GstPlayBin': <class 'playitslowly.pipeline.__main__.GstPlayBin'>, 'GstStreamVolume': <class 'playitslowly.pipeline.__main__.GstStreamVolume'>, ...}, init_globals=None, mod_name='__main__', mod_spec=ModuleSpec(name='playitslowly.app', loader=<_fro...lib/python3.4/dist-packages/playitslowly/app.py'), pkg_name='playitslowly', script_name=None)
   83                        __package__ = pkg_name,
   84                        __spec__ = mod_spec)
   85     exec(code, run_globals)
   86     return run_globals
   87 
builtinexec = <built-in function exec>
code = <code object <module> at 0xb71ee160, file "/usr/...n3.4/dist-packages/playitslowly/app.py", line 21>
run_globals = {'CONFIG_PATH': '/home/soren/.config/playitslowly.json', 'Config': <class '__main__.Config'>, 'GObject': <gi.module.DynamicModule 'GObject' from '/usr/li...-linux-gnu/girepository-1.0/GObject-2.0.typelib'>, 'Gdk': <gi.module.DynamicModule 'Gdk' from '/usr/lib/i386-linux-gnu/girepository-1.0/Gdk-3.0.typelib'>, 'Gio': <gi.module.DynamicModule 'Gio' from '/usr/lib/i386-linux-gnu/girepository-1.0/Gio-2.0.typelib'>, 'Gst': <gi.module.DynamicModule 'Gst' from '/usr/lib/girepository-1.0/Gst-1.0.typelib'>, 'GstColorBalance': <class 'playitslowly.pipeline.__main__.GstColorBalance'>, 'GstNavigation': <class 'playitslowly.pipeline.__main__.GstNavigation'>, 'GstPlayBin': <class 'playitslowly.pipeline.__main__.GstPlayBin'>, 'GstStreamVolume': <class 'playitslowly.pipeline.__main__.GstStreamVolume'>, ...}

 /usr/local/lib/python3.4/dist-packages/playitslowly/app.py in <module>()
  529     win.show_all()
  530     Gtk.main()
  531 
  532 if __name__ == "__main__":
  533     main()
main = <function main>

 /usr/local/lib/python3.4/dist-packages/playitslowly/app.py in main()
  520     )
  521 
  522     win = MainWindow(sink, config)
  523 
  524     if arguments:
win undefined
global MainWindow = <class '__main__.MainWindow'>
sink = 'autoaudiosink'
config = {}

 /usr/local/lib/python3.4/dist-packages/playitslowly/app.py in __init__(self=<MainWindow object at 0xb4d6f39c (__main__+MainWindow at 0x9ebf158)>, sink='autoaudiosink', config={})
  106         self.add_accel_group(self.accel_group)
  107 
  108         self.pipeline = Pipeline(sink)
  109 
  110         self.filedialog = myGtk.FileChooserDialog(None, self, Gtk.FileChooserAction.OPEN)
self = <MainWindow object at 0xb4d6f39c (__main__+MainWindow at 0x9ebf158)>
self.pipeline undefined
global Pipeline = <class 'playitslowly.pipeline.Pipeline'>
sink = 'autoaudiosink'

 /usr/local/lib/python3.4/dist-packages/playitslowly/pipeline.py in __init__(self=<Pipeline object at 0xb4d6fcfc (playitslowly+pipeline+Pipeline at 0x9de1060)>, sink='autoaudiosink')
   46             mygtk.show_error(_("You need to install the Gstreamer soundtouch elements for "
   47                     "play it slowly to. They are part of Gstreamer-plugins-bad. Consult the "
   48                     "README if you need more information.")).run()
   49             raise SystemExit()
   50 

NameError: name 'mygtk' is not defined
    __cause__ = None
    __class__ = <class 'NameError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of NameError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of NameError object>
    __doc__ = 'Name not found globally.'
    __eq__ = <method-wrapper '__eq__' of NameError object>
    __format__ = <built-in method __format__ of NameError object>
    __ge__ = <method-wrapper '__ge__' of NameError object>
    __getattribute__ = <method-wrapper '__getattribute__' of NameError object>
    __gt__ = <method-wrapper '__gt__' of NameError object>
    __hash__ = <method-wrapper '__hash__' of NameError object>
    __init__ = <method-wrapper '__init__' of NameError object>
    __le__ = <method-wrapper '__le__' of NameError object>
    __lt__ = <method-wrapper '__lt__' of NameError object>
    __ne__ = <method-wrapper '__ne__' of NameError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of NameError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of NameError object>
    __repr__ = <method-wrapper '__repr__' of NameError object>
    __setattr__ = <method-wrapper '__setattr__' of NameError object>
    __setstate__ = <built-in method __setstate__ of NameError object>
    __sizeof__ = <built-in method __sizeof__ of NameError object>
    __str__ = <method-wrapper '__str__' of NameError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("name 'mygtk' is not defined",)
    with_traceback = <built-in method with_traceback of NameError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/playitslowly/app.py", line 533, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/playitslowly/app.py", line 522, in main
    win = MainWindow(sink, config)
  File "/usr/local/lib/python3.4/dist-packages/playitslowly/app.py", line 108, in __init__
    self.pipeline = Pipeline(sink)
  File "/usr/local/lib/python3.4/dist-packages/playitslowly/pipeline.py", line 48, in __init__
    "README if you need more information.")).run()
NameError: name 'mygtk' is not defined

```

All dependencies are installed. What could cause this problem? 

Thanks :)

**Comment by trebmuh** [comment]
Could it be related to : https://github.com/jwagner/playitslowly/commit/aa8185b671ac4bec6066bb54b39952425e5f42de maybe?

**Comment by jwagner** [comment]
Sorry for the late reply on this. I was on holidays and I'm now playing catch up. There is two issues at play here:

- The stupid typo @trebmuh mentioned is the reason the program is failing.
- The reason it even gets to the point where it fails is because of a missing dependency, likely gst-plugins-bad1.0 / libgstsoundtouch.so missing.

How exactly did you install play it slowly?

**Comment by jwagner** [comment]
No update -> close.
